version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.5
    working_directory: ~/alphabetic-regex

    steps:
      - checkout
      - run:
          name: run tests
          command: |
            rake test
